openapi: 3.0.3
info:
  title: LH Calculator Excel API
  version: 2.0.0
  description: Excel-based calculation service with 141 fields for engineering and supply chain calculations

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /api/calculate:
    post:
      summary: Process calculation request
      description: Processes 141 fields through Excel formulas and returns calculated values
      operationId: calculateValues
      tags:
        - Calculations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
            examples:
              minimal:
                summary: Minimal valid request
                value:
                  tech_D27_type: 100
                  tech_E27_weightType: "E-113"
                  tech_F27_quantityType: "Целый ТА"
                  tech_G27_quantityType: "К4-750"
                  tech_H27_quantityType: "1/6"
                  tech_I27_quantityType: 5
                  tech_J27_quantityType: 10
                  tech_K27_quantity: 1
                  tech_L27_quantity: 2
                  tech_M27_material: 250
                  tech_P27_materialType: "AISI 316L"
                  tech_R27_materialThicknessType: "12Х18Н10Т"
                  tech_S27_materialThicknessType: "гофра"
                  tech_T27_materialThicknessType: 20
                  tech_U27_materialThicknessType: 1.2
                  tech_V27_thicknessType: 1.5
                  sup_F2_projectNumber: "PROJ-2024-001"
                  sup_D8_priceMaterial: 50000
                  sup_E8_priceMaterial: 55000
                  sup_K13_costQuantityNormTotal: 10
                  sup_P13_costQuantityMaterialNorm: 100000
                  sup_D78_massThickness: 25
                  sup_D43_priceTotal: 1000
                  sup_D44_price: 2000
                  sup_D45_price: 3000
                  sup_D46_price: 4000
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculationResponse'
        '422':
          description: Validation or processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check
      tags:
        - Monitoring
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time

  /api/metrics:
    get:
      summary: System metrics
      tags:
        - Monitoring
      responses:
        '200':
          description: Current metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  memory:
                    type: object
                    properties:
                      heapUsed:
                        type: number
                      heapTotal:
                        type: number
                      rss:
                        type: number
                  queue:
                    type: object
                    properties:
                      size:
                        type: integer
                      pending:
                        type: integer
                      processing:
                        type: integer
                  workers:
                    type: object
                    properties:
                      total:
                        type: integer
                      busy:
                        type: integer
                      available:
                        type: integer

  /api/fields/required:
    get:
      summary: Get required fields list
      tags:
        - Metadata
      responses:
        '200':
          description: List of required field names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/openapi.yaml:
    get:
      summary: Get OpenAPI specification
      tags:
        - Metadata
      responses:
        '200':
          description: OpenAPI specification in YAML format
          content:
            text/yaml:
              schema:
                type: string

  /api/openapi.json:
    get:
      summary: Get OpenAPI specification as JSON
      tags:
        - Metadata
      responses:
        '200':
          description: OpenAPI specification in JSON format
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    CalculationRequest:
      type: object
      required:
        # Engineering fields (технолог sheet) - Required
        - tech_D27_type
        - tech_E27_weightType
        - tech_F27_quantityType
        - tech_G27_quantityType
        - tech_H27_quantityType
        - tech_I27_quantityType
        - tech_J27_quantityType
        - tech_K27_quantity
        - tech_L27_quantity
        - tech_M27_material
        - tech_P27_materialType
        - tech_R27_materialThicknessType
        - tech_S27_materialThicknessType
        - tech_T27_materialThicknessType
        - tech_U27_materialThicknessType
        - tech_V27_thicknessType
        # Supply fields (снабжение sheet) - Required
        - sup_F2_projectNumber
        - sup_D8_priceMaterial
        - sup_E8_priceMaterial
        - sup_K13_costQuantityNormTotal
        - sup_P13_costQuantityMaterialNorm
        - sup_D78_massThickness
        - sup_D43_priceTotal
        - sup_D44_price
        - sup_D45_price
        - sup_D46_price
      properties:
        # Engineering fields (технолог sheet)
        tech_D27_type:
          type: number
          minimum: 0
          description: Equipment type identifier
        tech_E27_weightType:
          type: string
          pattern: '^[ЕК][-0-9А-Я*]*$'
          description: Equipment code (e.g., "Е-113", "К4-750")
        tech_F27_quantityType:
          type: string
          enum: ['Целый ТА', 'ШОТ-БЛОК', 'РЕИНЖ']
          description: Delivery type
        tech_G27_quantityType:
          type: string
          description: Equipment size specification
        tech_H27_quantityType:
          type: string
          pattern: '^\d+\/\d+$'
          description: Fraction specification (e.g., "1/6")
        tech_I27_quantityType:
          type: number
          minimum: 0
        tech_J27_quantityType:
          type: number
          minimum: 0
        tech_K27_quantity:
          type: number
          minimum: 0
        tech_L27_quantity:
          type: number
          minimum: 0
        tech_M27_material:
          type: number
          minimum: 0
          description: Material temperature rating
        tech_N27_pressureTestHot:
          type: number
          description: Hot pressure test value (computed)
        tech_O27_pressureTestCold:
          type: number
          description: Cold pressure test value (computed)
        tech_P27_materialType:
          type: string
          enum: ['AISI 316L', 'SMO 254', 'Hast-C276', 'Titanium', 'AISI 304', 'AISI316Ti', '904L']
          description: Primary material type
        tech_Q27_materialType:
          type: string
          description: Secondary material type (computed from P27)
        tech_R27_materialThicknessType:
          type: string
          enum: ['ст3', 'ст20', '09Г2С', '12Х18Н10Т', 'AISI 304', 'AISI 316L', 'AISI 321', 'AISI 316Ti']
          description: Material thickness type
        tech_S27_materialThicknessType:
          type: string
          enum: ['гофра', 'дв. лунка', 'од. лунка', 'шпилька', 'шпилька-лунка']
          description: Surface pattern type
        tech_T27_materialThicknessType:
          type: number
          minimum: 0
        tech_U27_materialThicknessType:
          type: number
          enum: [0.8, 1, 1.2, 1.5, 2, 3, 5]
          description: Material thickness in mm
        tech_V27_thicknessType:
          type: number
          enum: [0.8, 1, 1.2, 1.5, 2, 3, 5]
          description: Additional thickness specification

        # Project identification
        sup_F2_projectNumber:
          type: string
          description: Project number/identifier
          example: "PROJ-2024-001"
        sup_D9_priceMaterial:
          type: string
          enum: ['ст3', 'ст20', '09Г2С', '12Х18Н10Т', 'AISI 304', 'AISI 316L', 'AISI 321', 'AISI 316Ti']
          description: Price material specification

        # Supply fields - Required prices
        sup_D8_priceMaterial:
          type: number
          minimum: 0
          maximum: 1000000
          description: Material price per unit
        sup_E8_priceMaterial:
          type: number
          minimum: 0
          maximum: 1000000
          description: Alternative material price
        sup_K13_costQuantityNormTotal:
          type: number
          minimum: 0
          maximum: 10000
          description: Total normalized quantity cost
        sup_P13_costQuantityMaterialNorm:
          type: number
          minimum: 0
          maximum: 10000000
          description: Normalized material quantity cost
        sup_D78_massThickness:
          type: number
          minimum: 0
          maximum: 100
          description: Mass thickness parameter

        # Supply fields - Component costs
        sup_D43_priceTotal:
          type: number
          minimum: 0
        sup_D44_price:
          type: number
          minimum: 0
        sup_D45_price:
          type: number
          minimum: 0
        sup_D46_price:
          type: number
          minimum: 0

        # Additional required numeric fields
        sup_G43_priceMaterialInsulationTotal:
          type: number
          minimum: 0
        sup_G44_priceMaterialInsulation:
          type: number
          minimum: 0
        sup_G45_priceMaterialInsulation:
          type: number
          minimum: 0
        sup_H54_priceTotal:
          type: number
          minimum: 0
        sup_H55_priceTotal:
          type: number
          minimum: 0
        sup_H56_priceTotal:
          type: number
          minimum: 0
        sup_H57_priceTotal:
          type: number
          minimum: 0
        sup_I38_priceThicknessTotalType:
          type: number
          minimum: 0
        sup_I39_priceQuantityMaterialThicknessInsulationTotalType:
          type: number
          minimum: 0
        sup_I50_priceQuantityMaterialThicknessInsulationTotalSumType:
          type: number
          minimum: 0
        sup_I51_priceQuantityMaterialThicknessInsulationTotalSumType:
          type: number
          minimum: 0
        sup_I52_priceQuantityMaterialThicknessInsulationTotalSumType:
          type: number
          minimum: 0
        sup_I54_priceQuantityMaterialThicknessInsulationTotalType:
          type: number
          minimum: 0
        sup_I55_priceQuantityMaterialThicknessInsulationTotalType:
          type: number
          minimum: 0
        sup_I56_priceQuantityMaterialThicknessInsulationTotalType:
          type: number
          minimum: 0
        sup_I57_priceQuantityMaterialThicknessInsulationTotalType:
          type: number
          minimum: 0
        sup_K38_pricePipeTotal:
          type: number
          minimum: 0
        sup_K39_priceQuantityMaterialPipeInsulationTotal:
          type: number
          minimum: 0
        sup_M38_priceMaterialTotal:
          type: number
          minimum: 0
        sup_M39_quantityMaterialTotal:
          type: number
          minimum: 0
        sup_M44_priceMaterial:
          type: number
          minimum: 0
        sup_M45_priceMaterial:
          type: number
          minimum: 0
        sup_M46_priceQuantityMaterialSum:
          type: number
          minimum: 0
        sup_M51_priceQuantityMaterialTotalSum:
          type: number
          minimum: 0
        sup_M52_priceQuantityMaterialTotalSum:
          type: number
          minimum: 0
        sup_N50_priceQuantityWeightThicknessTotalSum:
          type: number
          minimum: 0
        sup_N51_priceQuantityWeightThicknessTotalSum:
          type: number
          minimum: 0
        sup_N52_priceQuantityWeightThicknessTotalSum:
          type: number
          minimum: 0
        sup_N54_quantityWeightThicknessTotal:
          type: number
          minimum: 0
        sup_N55_quantityWeightThicknessTotal:
          type: number
          minimum: 0
        sup_N56_quantityWeightThicknessTotal:
          type: number
          minimum: 0
        sup_N57_quantityWeightThicknessTotal:
          type: number
          minimum: 0
        sup_P45_priceMaterialTotal:
          type: number
          minimum: 0
        sup_F39_priceQuantityWeightMaterialInsulationTotal:
          type: number
          minimum: 0

        # Optional fields - Pressure ratings
        sup_C28_priceWeightThickness:
          type: string
          enum: ['Ру6', 'Ру10', 'Ру16', 'Ру25', 'Ру40', 'Ру63', 'Ру100', 'Ру160']
          description: Pressure rating
        sup_C29_priceWeightPipeThickness:
          type: string
          enum: ['Ру6', 'Ру10', 'Ру16', 'Ру25', 'Ру40', 'Ру63', 'Ру100', 'Ру160']
          description: Pipe pressure rating

        # Optional fields - Diameter codes
        sup_D28_priceWeightThickness:
          type: string
          enum: ['Ду25', 'Ду32', 'Ду40', 'Ду50', 'Ду65', 'Ду80', 'Ду100', 'Ду125', 'Ду150', 'Ду200', 'Ду250', 'Ду300', 'Ду350', 'Ду400', 'Ду450', 'Ду600', 'Ду800', 'Ду1000']
          description: Diameter code
        sup_D29_priceWeightPipe:
          type: string
          enum: ['Ду25', 'Ду32', 'Ду40', 'Ду50', 'Ду65', 'Ду80', 'Ду100', 'Ду125', 'Ду150', 'Ду200', 'Ду250', 'Ду300', 'Ду350', 'Ду400', 'Ду450', 'Ду600', 'Ду800', 'Ду1000']
          description: Pipe diameter code

      additionalProperties: true

    CalculationResponse:
      type: object
      required:
        - success
        - results
        - request_id
        - processing_time_ms
      properties:
        success:
          type: boolean
          enum: [true]
        results:
          type: object
          required:
            - calculated_values
            - total_cost
            - component_costs
          properties:
            calculated_values:
              type: object
              properties:
                tech_F27_quantityType:
                  type: string
                tech_G27_quantityType:
                  type: string
                tech_P27_materialType:
                  type: string
                tech_Q27_materialType:
                  type: string
                tech_R27_materialThicknessType:
                  type: string
                tech_S27_materialThicknessType:
                  type: string
                tech_U27_materialThicknessType:
                  type: number
            total_cost:
              type: number
              description: Total calculated cost
            component_costs:
              type: object
              properties:
                materials:
                  type: number
                processing:
                  type: number
                hardware:
                  type: number
                other:
                  type: number
        request_id:
          type: string
          pattern: '^req_\d{8}T\d{6}_[a-z0-9]{6}$'
        processing_time_ms:
          type: number
        metadata:
          type: object
          additionalProperties: true

    ErrorResponse:
      type: object
      required:
        - success
        - error
        - request_id
      properties:
        success:
          type: boolean
          enum: [false]
        error:
          type: string
          description: Error message
        details:
          type: object
          properties:
            field_errors:
              type: object
              additionalProperties:
                type: string
            missing_required_fields:
              type: array
              items:
                type: string
            excel_errors:
              type: array
              items:
                type: string
            processing_errors:
              type: array
              items:
                type: string
            error_type:
              type: string
              enum: ['VALIDATION_FAILED', 'EXCEL_CALCULATION_FAILED', 'EXCEL_FILE_NOT_FOUND', 'INTERNAL_ERROR', 'INVALID_REQUEST', 'INVALID_INPUT_DATA', 'MISSING_REQUIRED_FIELDS']
            queue_full:
              type: boolean
            retry_after:
              type: string
        request_id:
          type: string

tags:
  - name: Calculations
    description: Main calculation endpoints
  - name: Monitoring
    description: Health and metrics endpoints
  - name: Metadata
    description: API metadata and specifications