export interface ContractFieldNames {
  // Green cells - Supply inputs (user provided values)
  sup_D10_priceCostMaterial: string;
  sup_D11_priceCostMaterial: string;
  sup_D17_priceWeightThickness: string;
  sup_D38_priceQuantityTotal: string;
  sup_D43_priceTotal: number;
  sup_D44_price: number;
  sup_D45_price: number;
  sup_D46_price: number;
  sup_D78_massThickness: number;
  sup_D8_priceMaterial: number;
  sup_E101_priceMassPipeTotal: string;
  sup_E105_priceMassPipeTotal: string;
  sup_E20_priceWeightThicknessTotal: string;
  sup_E21_priceWeightThicknessTotal: string;
  sup_E26_priceWeightThickness: string;
  sup_E27_priceWeightThickness: string;
  sup_E8_priceMaterial: number;
  sup_F28_priceWeightThicknessTotal: string;
  sup_F29_priceWeightPipeTotal: string;
  sup_F2_parameter: number;
  sup_F30_priceWeightPipeTotal: string;
  sup_F31_priceWeightPipeTotal: string;
  sup_F32_priceWeightPipeTotal: string;
  sup_F33_priceWeightPipeTotal: string;
  sup_G43_priceMaterialInsulationTotal: number;
  sup_G44_priceMaterialInsulation: number;
  sup_G45_priceMaterialInsulation: number;
  sup_H54_priceTotal: number;
  sup_H55_priceTotal: number;
  sup_H56_priceTotal: number;
  sup_H57_priceTotal: number;
  sup_I38_priceThicknessTotalType: number;
  sup_I39_priceQuantityMaterialThicknessInsulationTotalType: number;
  sup_I44_priceMaterialThicknessInsulationTotalType: string;
  sup_I45_priceMaterialThicknessInsulationTotalType: string;
  sup_I46_priceQuantityMaterialThicknessInsulationTotalSumType: string;
  sup_I50_priceQuantityMaterialThicknessInsulationTotalSumType: number;
  sup_I51_priceQuantityMaterialThicknessInsulationTotalSumType: number;
  sup_I52_priceQuantityMaterialThicknessInsulationTotalSumType: number;
  sup_I54_priceQuantityMaterialThicknessInsulationTotalType: number;
  sup_I55_priceQuantityMaterialThicknessInsulationTotalType: number;
  sup_I56_priceQuantityMaterialThicknessInsulationTotalType: number;
  sup_I57_priceQuantityMaterialThicknessInsulationTotalType: number;
  sup_K13_costQuantityNormTotal: number;
  sup_K20_priceWeightThicknessTotal: string;
  sup_K21_priceWeightThicknessTotal: string;
  sup_K26_priceWeightThickness: string;
  sup_K27_priceWeightThickness: string;
  sup_K38_pricePipeTotal: number;
  sup_K39_priceQuantityMaterialPipeInsulationTotal: number;
  sup_L28_priceWeightThicknessTotalType: string;
  sup_L29_priceWeightPipeTotalType: string;
  sup_L30_priceWeightPipeTotalType: string;
  sup_L31_priceWeightPipeTotalType: string;
  sup_L32_priceWeightPipeTotalType: string;
  sup_L33_priceWeightPipeTotalType: string;
  sup_M38_priceMaterialTotal: number;
  sup_M39_quantityMaterialTotal: number;
  sup_M44_priceMaterial: number;
  sup_M45_priceMaterial: number;
  sup_M46_priceQuantityMaterialSum: number;
  sup_M51_priceQuantityMaterialTotalSum: number;
  sup_M52_priceQuantityMaterialTotalSum: number;
  sup_N50_priceQuantityWeightThicknessTotalSum: number;
  sup_N51_priceQuantityWeightThicknessTotalSum: number;
  sup_N52_priceQuantityWeightThicknessTotalSum: number;
  sup_N54_quantityWeightThicknessTotal: number;
  sup_N55_quantityWeightThicknessTotal: number;
  sup_N56_quantityWeightThicknessTotal: number;
  sup_N57_quantityWeightThicknessTotal: number;
  sup_P13_costQuantityMaterialNorm: number;
  sup_P45_priceMaterialTotal: number;
  sup_Q22_priceQuantityMaterialThicknessTotal: string;
  sup_Q23_priceMaterialThicknessTotal: string;
  sup_Q24_priceThicknessTotal: string;
  sup_T29_priceMaterial: string;
  sup_T30_priceMaterial: string;
  sup_T31_priceMaterial: string;
  sup_T33_priceMaterialPipe: string;
  sup_T34_priceMaterialTotal: string;
  sup_T35_priceMaterialTotal: string;
  sup_T37_price: string;
  sup_T38_price: string;
  sup_T39_priceQuantity: string;
  sup_T41_priceTotal: string;
  sup_T42_priceMaterialInsulationTotal: string;
  sup_T43_priceTotal: string;
  tech_D27_type: number;
  tech_E27_weightType: string;
  tech_H27_quantityType: string;
  tech_I27_quantityType: number;
  tech_J27_quantityType: number;
  tech_K27_quantity: number;
  tech_L27_quantity: number;
  tech_M27_material: number;
  tech_T27_materialThicknessType: number;

  // Orange cells - Engineering parameters
  sup_C28_priceWeightThickness: string;
  sup_C29_priceWeightPipeThickness: string;
  sup_D28_priceWeightThickness: string;
  sup_D29_priceWeightPipe: string;
  sup_D9_priceMaterial: string;
  sup_E19_priceWeightThicknessTotal: string;
  sup_E25_priceWeightThicknessTotal: string;
  sup_F39_priceQuantityWeightMaterialInsulationTotal: number;
  sup_I28_priceWeightThicknessType: string;
  sup_I29_priceWeightPipeThicknessType: string;
  sup_J28_priceQuantityWeightThicknessNormTotal: string;
  sup_J29_priceQuantityWeightPipeNormTotal: string;
  sup_K19_priceWeightThicknessTotal: string;
  sup_K25_priceWeightThicknessTotal: string;
  sup_P19_priceQuantityMaterialThickness: number;
  sup_P20_priceQuantityWeightMaterial: string;
  sup_P21_priceQuantityMaterial: string;
  sup_P22_priceQuantityMaterialTotal: string;
  sup_P29_priceMaterialTotal: string;
  sup_P33_priceMaterialPipeTotal: string;
  sup_P37_priceMaterialTotal: string;
  sup_P41_priceMaterialTotal: string;
  sup_Q29_priceThickness: string;
  sup_Q33_pricePipeThickness: string;
  sup_Q37_priceThickness: string;
  sup_Q41_priceThicknessTotal: string;
  sup_R29_price: string;
  sup_R33_pricePipe: string;
  sup_R37_price: string;
  sup_R41_priceTotal: string;
  tech_V27_thicknessType: number;

  // Yellow cells - Computed results
  tech_F27_quantityType: string;
  tech_G27_quantityType: string;
  tech_P27_materialType: string;
  tech_Q27_materialType: string;
  tech_R27_materialThicknessType: string;
  tech_S27_materialThicknessType: string;
  tech_U27_materialThicknessType: number;
}

export const FIELD_MAPPING = {
  // Maps field names to Excel cell addresses
  sup_C28_priceWeightThickness: 'снабжение!C28',
  sup_C29_priceWeightPipeThickness: 'снабжение!C29',
  sup_D10_priceCostMaterial: 'снабжение!D10',
  sup_D11_priceCostMaterial: 'снабжение!D11',
  sup_D17_priceWeightThickness: 'снабжение!D17',
  sup_D28_priceWeightThickness: 'снабжение!D28',
  sup_D29_priceWeightPipe: 'снабжение!D29',
  sup_D38_priceQuantityTotal: 'снабжение!D38',
  sup_D43_priceTotal: 'снабжение!D43',
  sup_D44_price: 'снабжение!D44',
  sup_D45_price: 'снабжение!D45',
  sup_D46_price: 'снабжение!D46',
  sup_D78_massThickness: 'снабжение!D78',
  sup_D8_priceMaterial: 'снабжение!D8',
  sup_D9_priceMaterial: 'снабжение!D9',
  sup_E101_priceMassPipeTotal: 'снабжение!E101',
  sup_E105_priceMassPipeTotal: 'снабжение!E105',
  sup_E19_priceWeightThicknessTotal: 'снабжение!E19',
  sup_E20_priceWeightThicknessTotal: 'снабжение!E20',
  sup_E21_priceWeightThicknessTotal: 'снабжение!E21',
  sup_E25_priceWeightThicknessTotal: 'снабжение!E25',
  sup_E26_priceWeightThickness: 'снабжение!E26',
  sup_E27_priceWeightThickness: 'снабжение!E27',
  sup_E8_priceMaterial: 'снабжение!E8',
  sup_F28_priceWeightThicknessTotal: 'снабжение!F28',
  sup_F29_priceWeightPipeTotal: 'снабжение!F29',
  sup_F2_parameter: 'снабжение!F2',
  sup_F30_priceWeightPipeTotal: 'снабжение!F30',
  sup_F31_priceWeightPipeTotal: 'снабжение!F31',
  sup_F32_priceWeightPipeTotal: 'снабжение!F32',
  sup_F33_priceWeightPipeTotal: 'снабжение!F33',
  sup_F39_priceQuantityWeightMaterialInsulationTotal: 'снабжение!F39',
  sup_G43_priceMaterialInsulationTotal: 'снабжение!G43',
  sup_G44_priceMaterialInsulation: 'снабжение!G44',
  sup_G45_priceMaterialInsulation: 'снабжение!G45',
  sup_H54_priceTotal: 'снабжение!H54',
  sup_H55_priceTotal: 'снабжение!H55',
  sup_H56_priceTotal: 'снабжение!H56',
  sup_H57_priceTotal: 'снабжение!H57',
  sup_I28_priceWeightThicknessType: 'снабжение!I28',
  sup_I29_priceWeightPipeThicknessType: 'снабжение!I29',
  sup_I38_priceThicknessTotalType: 'снабжение!I38',
  sup_I39_priceQuantityMaterialThicknessInsulationTotalType: 'снабжение!I39',
  sup_I44_priceMaterialThicknessInsulationTotalType: 'снабжение!I44',
  sup_I45_priceMaterialThicknessInsulationTotalType: 'снабжение!I45',
  sup_I46_priceQuantityMaterialThicknessInsulationTotalSumType: 'снабжение!I46',
  sup_I50_priceQuantityMaterialThicknessInsulationTotalSumType: 'снабжение!I50',
  sup_I51_priceQuantityMaterialThicknessInsulationTotalSumType: 'снабжение!I51',
  sup_I52_priceQuantityMaterialThicknessInsulationTotalSumType: 'снабжение!I52',
  sup_I54_priceQuantityMaterialThicknessInsulationTotalType: 'снабжение!I54',
  sup_I55_priceQuantityMaterialThicknessInsulationTotalType: 'снабжение!I55',
  sup_I56_priceQuantityMaterialThicknessInsulationTotalType: 'снабжение!I56',
  sup_I57_priceQuantityMaterialThicknessInsulationTotalType: 'снабжение!I57',
  sup_J28_priceQuantityWeightThicknessNormTotal: 'снабжение!J28',
  sup_J29_priceQuantityWeightPipeNormTotal: 'снабжение!J29',
  sup_K13_costQuantityNormTotal: 'снабжение!K13',
  sup_K19_priceWeightThicknessTotal: 'снабжение!K19',
  sup_K20_priceWeightThicknessTotal: 'снабжение!K20',
  sup_K21_priceWeightThicknessTotal: 'снабжение!K21',
  sup_K25_priceWeightThicknessTotal: 'снабжение!K25',
  sup_K26_priceWeightThickness: 'снабжение!K26',
  sup_K27_priceWeightThickness: 'снабжение!K27',
  sup_K38_pricePipeTotal: 'снабжение!K38',
  sup_K39_priceQuantityMaterialPipeInsulationTotal: 'снабжение!K39',
  sup_L28_priceWeightThicknessTotalType: 'снабжение!L28',
  sup_L29_priceWeightPipeTotalType: 'снабжение!L29',
  sup_L30_priceWeightPipeTotalType: 'снабжение!L30',
  sup_L31_priceWeightPipeTotalType: 'снабжение!L31',
  sup_L32_priceWeightPipeTotalType: 'снабжение!L32',
  sup_L33_priceWeightPipeTotalType: 'снабжение!L33',
  sup_M38_priceMaterialTotal: 'снабжение!M38',
  sup_M39_quantityMaterialTotal: 'снабжение!M39',
  sup_M44_priceMaterial: 'снабжение!M44',
  sup_M45_priceMaterial: 'снабжение!M45',
  sup_M46_priceQuantityMaterialSum: 'снабжение!M46',
  sup_M51_priceQuantityMaterialTotalSum: 'снабжение!M51',
  sup_M52_priceQuantityMaterialTotalSum: 'снабжение!M52',
  sup_N50_priceQuantityWeightThicknessTotalSum: 'снабжение!N50',
  sup_N51_priceQuantityWeightThicknessTotalSum: 'снабжение!N51',
  sup_N52_priceQuantityWeightThicknessTotalSum: 'снабжение!N52',
  sup_N54_quantityWeightThicknessTotal: 'снабжение!N54',
  sup_N55_quantityWeightThicknessTotal: 'снабжение!N55',
  sup_N56_quantityWeightThicknessTotal: 'снабжение!N56',
  sup_N57_quantityWeightThicknessTotal: 'снабжение!N57',
  sup_P13_costQuantityMaterialNorm: 'снабжение!P13',
  sup_P19_priceQuantityMaterialThickness: 'снабжение!P19',
  sup_P20_priceQuantityWeightMaterial: 'снабжение!P20',
  sup_P21_priceQuantityMaterial: 'снабжение!P21',
  sup_P22_priceQuantityMaterialTotal: 'снабжение!P22',
  sup_P29_priceMaterialTotal: 'снабжение!P29',
  sup_P33_priceMaterialPipeTotal: 'снабжение!P33',
  sup_P37_priceMaterialTotal: 'снабжение!P37',
  sup_P41_priceMaterialTotal: 'снабжение!P41',
  sup_P45_priceMaterialTotal: 'снабжение!P45',
  sup_Q22_priceQuantityMaterialThicknessTotal: 'снабжение!Q22',
  sup_Q23_priceMaterialThicknessTotal: 'снабжение!Q23',
  sup_Q24_priceThicknessTotal: 'снабжение!Q24',
  sup_Q29_priceThickness: 'снабжение!Q29',
  sup_Q33_pricePipeThickness: 'снабжение!Q33',
  sup_Q37_priceThickness: 'снабжение!Q37',
  sup_Q41_priceThicknessTotal: 'снабжение!Q41',
  sup_R29_price: 'снабжение!R29',
  sup_R33_pricePipe: 'снабжение!R33',
  sup_R37_price: 'снабжение!R37',
  sup_R41_priceTotal: 'снабжение!R41',
  sup_T29_priceMaterial: 'снабжение!T29',
  sup_T30_priceMaterial: 'снабжение!T30',
  sup_T31_priceMaterial: 'снабжение!T31',
  sup_T33_priceMaterialPipe: 'снабжение!T33',
  sup_T34_priceMaterialTotal: 'снабжение!T34',
  sup_T35_priceMaterialTotal: 'снабжение!T35',
  sup_T37_price: 'снабжение!T37',
  sup_T38_price: 'снабжение!T38',
  sup_T39_priceQuantity: 'снабжение!T39',
  sup_T41_priceTotal: 'снабжение!T41',
  sup_T42_priceMaterialInsulationTotal: 'снабжение!T42',
  sup_T43_priceTotal: 'снабжение!T43',
  tech_D27_type: 'технолог!D27',
  tech_E27_weightType: 'технолог!E27',
  tech_F27_quantityType: 'технолог!F27',
  tech_G27_quantityType: 'технолог!G27',
  tech_H27_quantityType: 'технолог!H27',
  tech_I27_quantityType: 'технолог!I27',
  tech_J27_quantityType: 'технолог!J27',
  tech_K27_quantity: 'технолог!K27',
  tech_L27_quantity: 'технолог!L27',
  tech_M27_material: 'технолог!M27',
  tech_P27_materialType: 'технолог!P27',
  tech_Q27_materialType: 'технолог!Q27',
  tech_R27_materialThicknessType: 'технолог!R27',
  tech_S27_materialThicknessType: 'технолог!S27',
  tech_T27_materialThicknessType: 'технолог!T27',
  tech_U27_materialThicknessType: 'технолог!U27',
  tech_V27_thicknessType: 'технолог!V27',
} as const;
